//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ohrc
{
    [Serializable]
    public class BodyStateMsg : Message
    {
        public const string k_RosMessageName = "ohrc_msgs/BodyState";
        public override string RosMessageName => k_RosMessageName;

        public BodyPartStateMsg head;
        public BodyPartStateMsg left_hand;
        public BodyPartStateMsg right_hand;

        public BodyStateMsg()
        {
            this.head = new BodyPartStateMsg();
            this.left_hand = new BodyPartStateMsg();
            this.right_hand = new BodyPartStateMsg();
        }

        public BodyStateMsg(BodyPartStateMsg head, BodyPartStateMsg left_hand, BodyPartStateMsg right_hand)
        {
            this.head = head;
            this.left_hand = left_hand;
            this.right_hand = right_hand;
        }

        public static BodyStateMsg Deserialize(MessageDeserializer deserializer) => new BodyStateMsg(deserializer);

        private BodyStateMsg(MessageDeserializer deserializer)
        {
            this.head = BodyPartStateMsg.Deserialize(deserializer);
            this.left_hand = BodyPartStateMsg.Deserialize(deserializer);
            this.right_hand = BodyPartStateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.head);
            serializer.Write(this.left_hand);
            serializer.Write(this.right_hand);
        }

        public override string ToString()
        {
            return "BodyStateMsg: " +
            "\nhead: " + head.ToString() +
            "\nleft_hand: " + left_hand.ToString() +
            "\nright_hand: " + right_hand.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
