//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ohrc
{
    [Serializable]
    public class GripperMsg : Message
    {
        public const string k_RosMessageName = "ohrc_msgs/Gripper";
        public override string RosMessageName => k_RosMessageName;

        public float angle;
        public float anglar_vel;
        public float force;
        public float position;
        public bool button;

        public GripperMsg()
        {
            this.angle = 0.0f;
            this.anglar_vel = 0.0f;
            this.force = 0.0f;
            this.position = 0.0f;
            this.button = false;
        }

        public GripperMsg(float angle, float anglar_vel, float force, float position, bool button)
        {
            this.angle = angle;
            this.anglar_vel = anglar_vel;
            this.force = force;
            this.position = position;
            this.button = button;
        }

        public static GripperMsg Deserialize(MessageDeserializer deserializer) => new GripperMsg(deserializer);

        private GripperMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.angle);
            deserializer.Read(out this.anglar_vel);
            deserializer.Read(out this.force);
            deserializer.Read(out this.position);
            deserializer.Read(out this.button);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.angle);
            serializer.Write(this.anglar_vel);
            serializer.Write(this.force);
            serializer.Write(this.position);
            serializer.Write(this.button);
        }

        public override string ToString()
        {
            return "GripperMsg: " +
            "\nangle: " + angle.ToString() +
            "\nanglar_vel: " + anglar_vel.ToString() +
            "\nforce: " + force.ToString() +
            "\nposition: " + position.ToString() +
            "\nbutton: " + button.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
