//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ohrc
{
    [Serializable]
    public class HeadStateMsg : Message
    {
        public const string k_RosMessageName = "ohrc_msgs/HeadState";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PoseMsg pose;
        public Geometry.TwistMsg twist;

        public HeadStateMsg()
        {
            this.pose = new Geometry.PoseMsg();
            this.twist = new Geometry.TwistMsg();
        }

        public HeadStateMsg(Geometry.PoseMsg pose, Geometry.TwistMsg twist)
        {
            this.pose = pose;
            this.twist = twist;
        }

        public static HeadStateMsg Deserialize(MessageDeserializer deserializer) => new HeadStateMsg(deserializer);

        private HeadStateMsg(MessageDeserializer deserializer)
        {
            this.pose = Geometry.PoseMsg.Deserialize(deserializer);
            this.twist = Geometry.TwistMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pose);
            serializer.Write(this.twist);
        }

        public override string ToString()
        {
            return "HeadStateMsg: " +
            "\npose: " + pose.ToString() +
            "\ntwist: " + twist.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
