//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Ohrc
{
    [Serializable]
    public class StateStampedMsg : Message
    {
        public const string k_RosMessageName = "ohrc_msgs/StateStamped";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public StateMsg state;

        public StateStampedMsg()
        {
            this.header = new Std.HeaderMsg();
            this.state = new StateMsg();
        }

        public StateStampedMsg(Std.HeaderMsg header, StateMsg state)
        {
            this.header = header;
            this.state = state;
        }

        public static StateStampedMsg Deserialize(MessageDeserializer deserializer) => new StateStampedMsg(deserializer);

        private StateStampedMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            this.state = StateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "StateStampedMsg: " +
            "\nheader: " + header.ToString() +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
